In [1]:
class geeks:
    course = "PYTHON"
    def new_course(obj):
        print("Purchase course: ", obj.course)

In [7]:
geeks.new_course()

TypeError: new_course() missing 1 required positional argument: 'obj'

In [25]:
import os
os.environ["PATH"]

'C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\2079342\\AppData\\Local\\atom\\bin;C:\\Users\\2079342\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\2079342\\AppData\\Local\\atom\\bin;C:\\Users\\2079342\\AppData\\Roaming\\Python\\Python38\\Scripts;C:\\Users\\2079342\\AppData\\Roaming\\Python\\Python38;'

In [7]:
os.getenv("dev")

In [1]:
import os

In [13]:
path = os.chdir(r"C:\Users\2079342\first_project")

In [15]:
path

In [12]:
"C:\Users\2079342\first_project\first_project\urls.py"

':'

In [23]:
import sys
os.path.dir(r"C:\Users\2079342")

AttributeError: module 'ntpath' has no attribute 'dir'

In [ ]:
#A Generator in Python is a function that returns an iterator using the Yield keyword. In this article, we will discuss how the generator function works in Python.

# Generator Function in Python
# A generator function in Python is defined like a normal function, but whenever it needs to generate a value, it does so with the yield keyword rather than return. If the body of a def contains yield, the function automatically becomes a Python generator function. 

# Create a Generator in Python
# In Python, we can create a generator function by simply using the def keyword and the yield keyword. The generator has the following syntax in Python:

In [ ]:
# Generator Object
# Python Generator functions return a generator object that is iterable, i.e., can be used as an Iterator. Generator objects are used either by calling the next method of the generator object or using the generator object in a “for in” loop.

# Example:

# In this example, we will create a simple generator function in Python to generate objects using the next() function.

In [18]:
def fib(limit):
    a,b = 0, 1
    while a < limit:
        yield a
        a,b = b, a+b

In [22]:
x = fib(5)
print(next(x))
print(next(x))
print(next(x))
print(next(x))
print(next(x))

0
1
1
2
3


In [28]:
def fab(limit):
    a, b = 0,1
    while a<limit:
        yield a
        a,b = b, a+b

In [29]:
x = fab(5)
for i in x:
    print(i)

0
1
1
2
3


In [48]:
# Decorators are a very powerful and useful tool in Python since it allows programmers to modify the behaviour of a function or class. Decorators allow us to wrap another function in order to extend the behaviour of the wrapped function, without permanently modifying it. But before diving deep into decorators let us understand some concepts that will come in handy in learning the decorators.

# First Class Objects
# In Python, functions are first class objects which means that functions in Python can be used or passed as arguments.
# Properties of first class functions:
# A function is an instance of the Object type.
# You can store the function in a variable.
# You can pass the function as a parameter to another function.
# You can return the function from a function.
# You can store them in data structures such as hash tables, lists, …

In [30]:
#Treating the functions as objects
def shout(text):
    return text.upper()

In [31]:
shout('hello')

'HELLO'

In [32]:
yell = shout

In [33]:
shout('hello')

'HELLO'

In [34]:
#Passing the function as an argument
def shout(text):
    return text.upper()
def whisper(text):
    return text.lower()
def greet(func):
    greeting = func("Hello this is arun vignesh, what is your name")
    print(greeting)

In [35]:
greet(shout)

HELLO THIS IS ARUN VIGNESH, WHAT IS YOUR NAME


In [36]:
greet(whisper)

hello this is arun vignesh, what is your name


In [37]:
#Returning functions from another function
def adder(x):
    def add(y):
        return x+y
    return add

In [44]:
adding = adder(15)

In [45]:
val = adding(10)

In [47]:
val

25

In [49]:
# Decorators
# As stated above the decorators are used to modify the behaviour of function or class. 
#In Decorators, functions are taken as the argument into another function and then called inside the wrapper function.

In [70]:
def hello_dec():
    print('Ggf')

In [60]:
hello_decorator = hello_dec()
hello_decorator

Ggf


In [143]:
#@hello_dec
def gfg_dec(func):
    print("First step")
    print("Its new")

In [154]:
a = gfg_dec(hello_dec)

First step
Its new


In [150]:
#@gfg_dec
def hello_dec():
    def new():
        print("Ggf")
        func()
        print('ITS NOT AN EMPTY')
    return new

In [137]:
hello_dec = hello_dec()
hello_dec

TypeError: 'NoneType' object is not callable

In [84]:
def hello_decorator(func):
    def inner1():
        print("This is before func execution")
        func()
        print("This is after execution")
    return inner1

In [85]:
def func_to_be_used():
    print("This is inside function")

In [86]:
func_used = hello_decorator(func_to_be_used)

In [87]:
func_used()

This is before func execution
This is inside function
This is after execution


In [138]:
def hello_decorator(func):
    def inner1():
        print("This is before func execution")
        func()
        print("This is after execution")
    return inner1

In [139]:
@hello_decorator
def func_to_be_used():
    print("This is inside function")

In [140]:
func_to_be_used()

This is before func execution
This is inside function
This is after execution


In [126]:
func_used()

This is before func execution
This is before func execution
This is inside function
This is after execution
This is after execution


In [174]:
import time
import math
def cal_time(func):
    def inner1(*args,**kwargs):
        begin = time.time()
        #func(*args,**kwargs)
        func(*args, **kwargs)
        end = time.time()
        print("Total time taken in : ", func.__name__, end - begin)
    return inner1

In [175]:
@cal_time
def factorial(num):
    time.sleep(2)
    print(math.factorial(num))

In [176]:
factorial(10)

3628800
Total time taken in :  factorial 2.000540018081665


In [185]:
def hello_decorator(func):
    def inner1(*args, **kwargs):
        print("Before excecution")
        returned_val = func(*args, **kwargs)
        print("After excecution")
        return returned_val
    return inner1

In [186]:
def sum_of_two_numbers(a,b):
    print("This is inside function")
    return a+b

In [187]:
a, b = 10,15

In [188]:
print("Sum of two numbers is ", sum_of_two_numbers(a,b))

This is inside function
Sum of two numbers is  25


In [189]:
@hello_decorator
def sum_of_two_numbers(a,b):
    print("This is inside function")
    return a+b

In [190]:
print("Sum of two numbers is ", sum_of_two_numbers(a,b))

Before excecution
This is inside function
After excecution
Sum of two numbers is  25


In [197]:
def hello_dec(func):
    def inner():
        x = func()
        return x*x
    return inner
def hello_dec2(func):
    def inner():
        s = func()
        return 2*s
    return inner

In [198]:
@hello_dec
@hello_dec2
def num():
    return 10

In [199]:
num()

400

In [200]:
@hello_dec2
@hello_dec
def num():
    return 10

In [201]:
num()

200

In [202]:
class Person:
  name = "John"
  age = 36
  country = "Norway"

In [205]:
x = getattr(Person, 'age')

In [206]:
x

36

In [212]:
string = "Arun Vignesh"
iter_str = iter(string)
next(iter_str)
next(iter_str)

'r'

In [214]:
# constructor - __init__(self)
# decorator - @dec_func
#             def num():
#                 return 10
# generator - yield, next()
# iterator - iter(), next()

In [216]:
import numpy as np

In [228]:
arr = np.empty([4,2], dtype=np.uint16)

In [229]:
arr

array([[53691, 33665],
       [49409,  1035],
       [30317, 22277],
       [47496, 30631]], dtype=uint16)

In [230]:
arr.shape

(4, 2)

In [231]:
arr.ndim

2

In [232]:
arr.itemsize

2

In [233]:
arr1 = np.arange(100,200,10)
arr1

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [237]:
arr1.reshape(2,5)

array([[100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [250]:
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[...,2]

array([33, 66, 99])

In [261]:
arr = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
arr1 = (([87, 88, 99]))
#np.insert(arr, 1, arr1, axis=1)

In [262]:
np.delete(arr, 1, axis=1)
arr = np.array([[10,10,10]])

In [263]:
arr

array([[10, 10, 10]])

In [27]:
class Animal:
    def __init__(self, a ,b, c):
        self.a = a
        self.b = b
        self.c = c
    def word(self, a, b, c):
        return a+b+c
    def add(self, a, b, c):
        return a+b+c

In [28]:
animal = Animal(5,6,7)
animal.word(5, 6, 7)

18